// List generated by ChatGPT 5.0

export type EquipmentOption = {
  id: string;
  label: string;
  description: string;
};

export type EquipmentCategory = {
  id: string;
  title: string;
  items: EquipmentOption[];
};

export const EQUIPMENT_CATEGORIES: EquipmentCategory[] = [
  {
    id: "bars_free_weights",
    title: "Bars & Free Weights",
    items: [
      {
        id: "olympic_barbell",
        label: "Olympic Barbell",
        description: "20 kg, general-purpose bar for squats, bench, and deadlifts.",
      },
      {
        id: "power_bar",
        label: "Power Bar",
        description: "Stiffer bar with aggressive knurling; common in powerlifting competition.",
      },
      {
        id: "deadlift_bar",
        label: "Deadlift Bar",
        description: "Longer bar with more whip, optimized for deadlifts.",
      },
      {
        id: "ssb",
        label: "Safety Squat Bar (SSB)",
        description: "Padded, cambered specialty bar that eases shoulder strain on squats.",
      },
      {
        id: "trap_bar",
        label: "Trap Bar / Hex Bar",
        description: "Neutral-grip deadlifts, carries, and shrugs.",
      },
      {
        id: "ez_curl_bar",
        label: "EZ Curl Bar",
        description: "Angled bar for curls and triceps work.",
      },
      {
        id: "dumbbells",
        label: "Dumbbells",
        description: "Fixed or adjustable; universal utility for unilateral work.",
      },
      {
        id: "kettlebells",
        label: "Kettlebells",
        description: "For swings, presses, pulls, and explosive work.",
      },
    ],
  },
  {
    id: "benches_racks",
    title: "Benches & Racks",
    items: [
      { id: "flat_bench", label: "Flat Bench", description: "Standard bench for pressing and dumbbell work." },
      { id: "adjustable_bench", label: "Adjustable Bench", description: "Incline/decline options for variation." },
      { id: "power_rack", label: "Power Rack / Squat Rack", description: "Rack for squats, bench, pull-ups, and safety pins." },
      { id: "deadlift_platform", label: "Deadlift Platform", description: "Platform for pulls; protects floor and dampens noise." },
    ],
  },
  {
    id: "machines_cables",
    title: "Machines & Cables",
    items: [
      { id: "functional_trainer", label: "Cable Machine / Functional Trainer", description: "Versatile cable stacks for pushes, pulls, and rotations." },
      { id: "smith_machine", label: "Smith Machine", description: "Guided bar path for controlled presses and squats." },
      { id: "leg_press", label: "Leg Press Machine", description: "Compound lower-body machine emphasizing quads & glutes." },
      { id: "lat_pulldown", label: "Lat Pulldown Machine", description: "Vertical pulling for lats and upper back." },
      { id: "seated_row", label: "Seated Row Machine", description: "Horizontal pulling for mid-back." },
    ],
  },
  {
    id: "plates_accessories",
    title: "Plates & Accessories",
    items: [
      { id: "bumper_plates", label: "Bumper Plates", description: "Rubber-coated plates for safer drops and Olympic lifts." },
      { id: "iron_plates", label: "Iron Plates", description: "Classic cast-iron plates; slimmer profile." },
      { id: "collars_clamps", label: "Collars / Clamps", description: "Secures plates on the bar for safety." },
      { id: "resistance_bands", label: "Resistance Bands", description: "Assistance/resistance, warm-ups, and accessory work." },
      { id: "chains", label: "Chains", description: "Accommodating resistance for barbell lifts." },
    ],
  },
];

// flat list
export const EQUIPMENT: EquipmentOption[] = EQUIPMENT_CATEGORIES.flatMap(c => c.items);

// Lookup for description
export const EQUIPMENT_BY_ID = new Map<string, EquipmentOption>(
  EQUIPMENT.map(e => [e.id, e])
);
